// Complete Product jobs seed data - Auto-loads on first visit
export const PRODUCT_SEED_DATA = `Company,Category,Country,Product_Domain,Target_Role,Hiring_Season,Internship_Type,Conversion_Potential,Case_Interview_Focus,SQL_Level,Product_Sense_Level,Analytics_Tools,Stipend_Monthly,Expected_FTE_CTC,Referral_Friendly,Referral_Status,Referral_Name,LinkedIn_Profile,Application_Status,Followup_Date,Careers_Page,Notes,Priority
Google,BigTech,Global,Consumer Products,APM Intern,Summer/Winter,Structured Program,High,Product Design + Metrics,Medium,Advanced,"SQL, GA","₹1L+","30+ LPA",Low,Not Contacted,,,Not Applied,,https://careers.google.com,Ultra competitive,5
Microsoft,BigTech,Global,Cloud/OS,Program Manager Intern,Summer/Winter,Structured Program,High,Execution + Stakeholders,Medium,Advanced,"SQL, Excel","₹80k","25+ LPA",Medium,Not Contacted,,,Not Applied,,https://careers.microsoft.com,PM ≠ Product sometimes,5
Amazon,BigTech,Global,Marketplace/Product Ops,Product Ops Intern,Summer,Structured Program,Medium,Metrics + Execution,Medium,Intermediate,"SQL, Excel","₹60k","20+ LPA",Medium,Not Contacted,,,Not Applied,,https://amazon.jobs,Ops heavy,4
Uber,Product,Global,Consumer Tech,Product Analyst Intern,Rolling,Team Based,High,Funnel + Metrics,High,Advanced,"SQL, Looker","₹80k","25+ LPA",High,Not Contacted,,,Not Applied,,https://uber.com/careers,Strong analytics culture,5
Atlassian,Product,Global,DevTools,Product Ops Intern,Rolling,Team Based,High,User journeys,Medium,Advanced,"SQL, GA","₹70k","22+ LPA",High,Not Contacted,,,Not Applied,,https://atlassian.com/careers,Great PM culture,5
Intuit,BigTech,Global,FinTech,Product Analyst Intern,Summer,Structured Program,High,Metrics + Experiments,Medium,Advanced,"SQL, Tableau","₹70k","22+ LPA",Medium,Not Contacted,,,Not Applied,,https://careers.intuit.com,Finance products,5
Flipkart,Indian Product,India,Ecommerce,Product Analyst Intern,Rolling,Team Based,High,Funnel + Retention,High,Advanced,"SQL, Excel","₹50k","20–25 LPA",High,Not Contacted,,,Not Applied,,https://flipkartcareers.com,Best entry,5
Meesho,Indian Product,India,Ecommerce,Product Ops Intern,Rolling,Fast Hiring,High,Execution + Metrics,Medium,Intermediate,"SQL, Sheets","₹40k","18–22 LPA",High,Not Contacted,,,Not Applied,,https://careers.meesho.com,Very fresher friendly,5
Swiggy,Indian Product,India,Consumer Tech,Product Analyst Intern,Rolling,Team Based,High,User funnels,High,Advanced,"SQL, Amplitude","₹50k","20+ LPA",High,Not Contacted,,,Not Applied,,https://careers.swiggy.com,Strong PM ladder,5
Zomato,Indian Product,India,Consumer Tech,Product Ops Intern,Rolling,Team Based,Medium,Ops + UX,Medium,Intermediate,"SQL, Excel","₹40k","18+ LPA",Medium,Not Contacted,,,Not Applied,,https://zomato.com/careers,Ops exposure,4
Razorpay,FinTech,India,Payments,Product Analyst Intern,Rolling,Referral Driven,High,Metrics + Payments flows,High,Advanced,"SQL, Metabase","₹50k","22+ LPA",High,Not Contacted,,,Not Applied,,https://razorpay.com/jobs,Great PM culture,5
PhonePe,FinTech,India,Payments,Product Analyst Intern,Rolling,Referral Driven,High,Funnel + Growth,High,Advanced,"SQL, Looker","₹50k","22+ LPA",High,Not Contacted,,,Not Applied,,https://phonepe.com/careers,Strong data culture,5
Paytm,FinTech,India,Payments,Product Ops Intern,Rolling,Mass Hiring,Medium,Ops + Metrics,Medium,Intermediate,"SQL, Excel","₹35k","15–18 LPA",Medium,Not Contacted,,,Not Applied,,https://paytm.com/careers,Team dependent,4
CRED,FinTech,India,Consumer FinTech,Product Strategy Intern,Rolling,Referral Driven,High,User behavior,Medium,Advanced,"SQL, GA","₹50k","20+ LPA",High,Not Contacted,,,Not Applied,,https://cred.club/careers,Case heavy,4
Groww,FinTech,India,Investments,Product Analyst Intern,Rolling,Referral Driven,High,Metrics + UX,High,Advanced,"SQL, Tableau","₹45k","18–22 LPA",High,Not Contacted,,,Not Applied,,https://groww.in/careers,Great analyst path,5
Zeta,FinTech Infra,India,Banking Infra,Product Ops Intern,Rolling,Referral Driven,Medium,Execution + APIs,Medium,Intermediate,"SQL, Excel","₹40k","18–22 LPA",High,Not Contacted,,,Not Applied,,https://careers.zeta.tech,Infra exposure,4
Juspay,FinTech Infra,India,Payments Infra,Product Ops Intern,Rolling,Referral Driven,Medium,Flows + Reliability,Medium,Intermediate,"SQL, Excel","₹40k","18–22 LPA",High,Not Contacted,,,Not Applied,,https://juspay.in/careers,Infra PM path,4
BrowserStack,SaaS,India,DevTools,Product Ops Intern,Rolling,Team Based,High,User feedback loops,Medium,Intermediate,"SQL, GA","₹40k","18+ LPA",High,Not Contacted,,,Not Applied,,https://browserstack.com/careers,Good stepping stone,4
Postman,SaaS,India,API Platform,Product Analyst Intern,Rolling,Team Based,High,Developer experience,Medium,Advanced,"SQL, GA","₹45k","20+ LPA",High,Not Contacted,,,Not Applied,,https://postman.com/careers,Dev-first PMs,5
Zoho,SaaS,India,Enterprise,Product Analyst Intern,Rolling,Direct Hiring,Medium,Requirements + UX,Low,Intermediate,"SQL, Excel","₹30k","12–15 LPA",Low,Not Contacted,,,Not Applied,,https://careers.zoho.com,Fundamentals,3
Freshworks,SaaS,India,CRM,Product Ops Intern,Rolling,Team Based,Medium,Execution + Metrics,Medium,Intermediate,"SQL, Excel","₹35k","15–18 LPA",Medium,Not Contacted,,,Not Applied,,https://freshworks.com/careers,Enterprise SaaS,3
Zepto,Startup,India,Quick Commerce,Product Ops Intern,Rolling,Startup Style,Medium,Ops + Growth,Medium,Intermediate,"SQL, Sheets","₹30k","12–15 LPA",High,Not Contacted,,,Not Applied,,https://zepto.co/careers,Fast execution,3
Blinkit,Startup,India,Quick Commerce,Product Ops Intern,Rolling,Team Based,Medium,Ops + Metrics,Medium,Intermediate,"SQL, Sheets","₹30k","12–15 LPA",Medium,Not Contacted,,,Not Applied,,https://blinkit.com/careers,Ops heavy,3
FamPay,FinTech,India,Youth FinTech,Product Analyst Intern,Rolling,Startup Style,Medium,User behavior,Medium,Intermediate,"SQL, GA","₹30k","12–15 LPA",High,Not Contacted,,,Not Applied,,https://fampay.in/careers,Early PM exposure,3
Navi,FinTech,India,Lending,Product Ops Intern,Rolling,Team Based,Medium,Execution + Risk,Medium,Intermediate,"SQL, Excel","₹30k","12–15 LPA",Medium,Not Contacted,,,Not Applied,,https://navi.com/careers,Fast org,3
Fi Money,FinTech,India,NeoBank,Product Analyst Intern,Rolling,Team Based,Medium,User journeys,Medium,Intermediate,"SQL, GA","₹35k","15–18 LPA",Medium,Not Contacted,,,Not Applied,,https://fi.money/careers,Good PM ladder,3`;
